name: DAST Scan with OWASP ZAP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

permissions:
  issues: write
  contents: read

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Run DAST Scan

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: ZAP Full Scan
        # uses: zaproxy/action-full-scan@v0.12.0
        uses: zaproxy/action-baseline@v0.14.0
     

#  OWASP ZAP Action use 

#  internally
# ZAP Download
# Docker Container Start
# Spider
# Passive Scan
# Active Scan
# Report Generate
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'https://preview.owasp-juice.shop/'
          rules_file_name: 'rules.tsv'
# Rule Enable

# Rule Disable

# Ignore

# FAIL

# WARN

# INFO
          # fail_action: false
          fail_action: true
          issue_title: 'DAST Vulnerabilities Found'