name: DAST Scan with OWASP ZAP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Run DAST Scan

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'https://preview.owasp-juice.shop/'
          rules_file_name: 'rules.tsv'
          fail_action: False 
          # fail_action: False 
          # issue_title: 'DAST Vulnerabilities Found'